backend:
  name: github
  branch: master
  repo: LeoCantThinkOfAName/the-pedestrians

media_folder: static/assets
public_folder: assets

collections:
  - label: "中文版"
    name: "tw-post"
    folder: "contents/zh-TW"
    filter: { field: "lang", value: "zh-TW" }
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - {
          label: "語系",
          name: "lang",
          widget: "select",
          options: ["zh-TW", "en"],
        }
      - { label: "標題", name: "title", widget: "string" }
      - { label: "發布日期", name: "date", widget: "datetime" }
      - { label: "封面圖片", name: "cover", widget: "image" }
      - { label: "網址字串", name: "slug", widget: "string" }
      - { label: "標籤", name: "tags", widget: "list" }
      - { label: "簡介", name: "description", widget: "string" }
      - { label: "本文", name: "body", widget: "markdown" }
  - label: "英文版"
    name: "en-post"
    folder: "contents/en"
    filter: { field: "lang", value: "en" }
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - {
          label: "語系",
          name: "lang",
          widget: "select",
          options: ["zh-TW", "en"],
        }
      - { label: "標題", name: "title", widget: "string" }
      - { label: "發布日期", name: "date", widget: "datetime" }
      - { label: "封面圖片", name: "cover", widget: "image" }
      - { label: "網址字串", name: "slug", widget: "string" }
      - { label: "標籤", name: "tags", widget: "list" }
      - { label: "簡介", name: "description", widget: "string" }
      - { label: "本文", name: "body", widget: "markdown" }
