backend:
  name: github
  branch: master
  repo: LeoCantThinkOfAName/the-pedestrians

media_folder: static/assets
public_folder: assets

collections:
  - label: "中文版"
    name: "tw-post"
    folder: "contents/zh-TW"
    filter: { field: "lang", value: "zh-TW" }
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Language",
          name: "lang",
          widget: "select",
          options: ["en", "zh-TW"],
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Cover Image", name: "cover", widget: "image" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "英文版"
    name: "en-post"
    folder: "contents/en"
    filter: { field: "lang", value: "en" }
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Language",
          name: "lang",
          widget: "select",
          options: ["en", "zh-TW"],
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Cover Image", name: "cover", widget: "image" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
